#!/usr/bin/env python

import ros_graph_parser.snapshot as rg
import ros_graph_parser.srv as rg_srv
import rospy


class RosGraphNode():

    def __init__(self):
        rospy.Service('scan_ros_graph', rg_srv.Scan, self.create_snapshot)
    
    def create_snapshot(self, request):
        answer = rg_srv.ScanResponse()
        answer.success, answer.message, answer.rosgraph = self._create_snapshot()
        return answer

    def _create_snapshot(self):
        try:
            snapshot = rg.create_ros_graph_snapshot()
            dump = dict()
            dump['nodes']=dict()
            for node in snapshot:
                dump['nodes'][node.name] = node.dump_yaml()
            return True, "Scanning Succeeded", str(dump)
        except:
            return False, "Scanning Failed", ""


if __name__ == "__main__":
    rospy.init_node("ros_graph_parser_node")
    RosGraphNode()
    rospy.spin()