#!/usr/bin/env python

import ros_graph_parser.snapshot as rg
import ros_graph_parser.srv as rg_srv
import rospy


class RosGraphNode():

    def __init__(self):
        rospy.Service('get_ros_model', rg_srv.GetROSModel,
                      self.get_ros_model)

        rospy.Service('get_rossystem_model', rg_srv.GetROSSystemModel,
                      self.get_rossystem_model)

    def get_ros_model(self, request):
        answer = rg_srv.GetROSModelResponse()
        answer.success, answer.message, answer.model = rg.create_java_ros_model()
        return answer

    def get_rossystem_model(self, request):
        answer = rg_srv.GetROSSystemModelResponse()
        answer.success, answer.message, answer.model = rg.create_java_system_model()
        return answer


if __name__ == "__main__":
    rospy.init_node("ros_graph_parser_node")
    RosGraphNode()
    rospy.spin()
