#!/usr/bin/env python

import ros_graph_parser.snapshot as rg
import rospkg
import argparse
import os


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Save the parsed ROS graph into '.yml' file in the package result folder. ")
    parser.add_argument('file_name', metavar='f', type=str, default='ros_snapshot.yml', help="name of the file to save the results")
    args = parser.parse_args()
    path = rospkg.RosPack().get_path('ros_graph_parser')
    file_ = os.path.join(path+"/result",args.file_name)
    snapshot = rg.create_ros_graph_snapshot()
    rg.dump_yaml(snapshot, file_)
